StudentAttendancePortal/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'welcome#index'
  resources :teachers, :subjects, :students, :attendances
  #patch 'teachers/:id', to: 'teachers#update'
end

StudentAttendancePortal/app/models/teacher.rb
class Teacher < ApplicationRecord
  has_one :subject, dependent: :nullify
  validates :email, presence: { message: I18n.t("blank") }, uniqueness: { message: I18n.t("unique") }, format: { with: EMAIL_REGEX, message: I18n.t("invalid")}
  validates :password, format: { with: PASSWORD_REGEX, message: I18n.t("pattern") }
  validates :password, confirmation: true
  validates :mobile_no, uniqueness: true, format: { with: MOBILE_NO_REGEX, message: I18n.t("invalid")}

  after_save :send_welcome_mail

  def send_welcome_mail
    TeacherMailer.with(teacher: self).welcome_email.deliver_now
  end

end

StudentAttendancePortal/app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  protect_from_forgery with: :null_session
  before_action :find_teacher, only: %i[show update destroy]

  def index
    @teachers = Teacher.all
  end

  def create
    @teacher = Teacher.new(teacher_params)
    respond_to do |format|
      if @teacher.save
        format.html { redirect_to teacher_url(@teacher), notice: "Teacher was successfully created." }
        format.json { render :show, status: :created, location: @teacher }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end   
  end

   # GET /teachers/1 or /teachers/1.json
   def show
     @teacher = Teacher.find params[:id]
   end
 
   # GET /teachers/new
   def new
     @teacher = Teacher.new
   end
 
   # GET /teachers/1/edit
   def edit
    @teacher = Teacher.find(params[:id])
    render :edit
   end

  

  def update
    @teacher = Teacher.find(params[:id])
    if @teacher.update(teacher_params)
      redirect_to(@teacher)
    else
      render "edit"
    end
  end

  def destroy   
    @teacher.destroy
    respond_to do |format|
      format.html { redirect_to teachers_url, notice: "Teacher was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def teacher_params
    params.require(:teacher).permit(:name, :email, :password, :dob, :gender, :address, :mobile_no)
  end

  def find_teacher
    @teacher = Teacher.find params[:id]
  rescue ActiveRecord::RecordNotFound => e
    render json: { meaasge: I18n.t('controller.present') }
  end
end

StudentAttendancePortal/app/helpers/teachers_helper.rb
module TeachersHelper
end

StudentAttendancePortal/app/views/teachers/_form.html.erb
<%= form_with(model: teacher) do |form| %>
  <table>
    <tr>
      <div>
        <td><%= form.label :name, "Name: " %></td>
        <td><%= form.text_field :name %></td>
      </div>
    </tr>
    <tr>
      <div>
        <td> <%= form.label :password, 'Password: '%></td>
        <td><%= form.password_field :password %></td>
      </div>
    </tr>
    <tr>
      <div>
        <td><%= form.label :password, 'Confirm -Password: '%></td>
        <td><%= form.password_field :password_confirmation %></td>
      </div>
    </tr>
    <tr>
      <div>
        <td><%= form.label :email,"Email: " %></td>
        <td><%= form.text_field :email %></td>
      </div>
    </tr>
    <tr>
      <div>
        <td><%= form.radio_button :gender, "Female" %>
          <%= form.label :Female, "Female" %></td>
        <td><%= form.radio_button :gender, "Male" %>
          <%= form.label :Male, "Male" %></td>
      </div>
    </tr>
    <tr>
      <div>
        <td><%= form.label :dob, "Date of birth: " %></td>
        <td><%= form.date_field :dob, as: :date, value: form.object.try(:strftime,"%m/%d/%Y")%></td>
      </div>
    </tr>
    <tr>
      <div>
        <td><%= form.label :mobile_no, 'Mobile number: ' %></td>
        <td> <%= form.text_field :mobile_no %></td>
      </div>
    </tr>
    <tr>
      <div>
        <td><%= form.label :address,'Address: ' %></td>
        <td><%= form.text_field :address %></td>
      </div>
    </tr>
  </table></br>

  <div class="col-3", style="margin: 0 auto;">
    <%= form.submit class: "btn btn-warning"%>
  </div>
<% end %>

StudentAttendancePortal/app/views/teachers/edit.html.erb
<div style="padding: 10px;">
  <%= link_to "Back to Teachers", teachers_path, class: "btn btn-success" %>    
</div>

<div class="col-6" style="margin : 0 auto;">
  <h1>Editing Teacher</h1></br>
  <%= render "form", teacher: @teacher %>
</div>

StudentAttendancePortal/app/views/teachers/index.html.erb
<div style="padding: 10px;">
  <%= link_to "HOME", welcome_index_path, class: "btn btn-success" %>    
</div>

<div class="col-4" style="margin : 0 auto; padding: 10px">
  <h1>All Teachers data</h1></br>
</div>
<table class="table table-striped">
  <thead class="thead-light">
    <tr>
      <td>ID</td>
      <td>Name</td>
      <td>Email</td>
      <td>Mobile number</td>
    </tr>
  </thead>
  <tbody>
    <% @teachers.each do |teacher| %>
      <tr>
        <td><%=teacher.id%></td>
        <td><%= teacher.name %></td>
        <td><%= teacher.email %></td> 
        <td><%= teacher.mobile_no %></td>
        <td><%= link_to 'show', teacher%></td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="col-2" style="margin : 0 auto; padding: 10px">
<%= link_to 'Add new', new_teacher_path, class: "btn btn-success" %>
</div>

StudentAttendancePortal/app/views/teachers/new.html.erb
<div class="col-5"style="padding: 40px;">
  <%= link_to "Back to Teachers", teachers_path, class: "btn btn-success" %>    
</div>

<div class="col-4" style="margin : 0 auto;">
  <div class="col-8" style="margin : 0 auto;">
    <h1>New Teacher</h1></br>
  </div>
  <%= render "form", teacher: @teacher %>
</div>

StudentAttendancePortal/app/views/teachers/show.html.erb
<div style="padding: 10px;">
  <%= link_to "Back to Teachers", teachers_path, class: "btn btn-success" %>   
</div>

<div class="col-6" style="margin : 0 auto;">
  <h2><%= @teacher.name %>'s  Details</h2></br></br>
  <h4>Name: <%= @teacher.name %></h4>
  <h4>Email: <%= @teacher.email %></h4>
  <h4>Date of birth: <%= @teacher.dob %></h4>
  <h4>Gender: <%= @teacher.gender %></h4>
  <h4>Address: <%= @teacher.address %></h4>
  <h4>Mobile number: <%= @teacher.mobile_no %></h4></br></br>
  <div class="d-flex justify-content-center">  
    <div class="col-2">
      <%= link_to "Edit", edit_teacher_path(@teacher), class: "btn btn-warning"%> 
    </div>
    <div class="col-3">
      <%= button_to "Destroy", @teacher, class: "btn btn-danger", data: {:confirm => 'Are you sure?'}, method: :delete %>
    </div>
  </div>
</div>