StudentAttendancePortal/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'welcome#index'
  resources :teachers, :subjects, :students, :attendances
  #patch 'teachers/:id', to: 'teachers#update'
end

StudentAttendancePortal/app/models/student.rb
class Student < ApplicationRecord
  has_many :subjects_students
  has_many :subjects, through: :subjects_students
  has_one :attendance, dependent: :nullify

  validates :email, presence: { message: I18n.t("blank") }, uniqueness: { message: I18n.t("unique") }, format: { with: EMAIL_REGEX, message: I18n.t("invalid")}
  validates :password, format: { with: PASSWORD_REGEX, message: I18n.t("pattern") }
  validates :password, confirmation: true
  
  after_save :send_welcome_mail

  def send_welcome_mail
    StudentMailer.with(student: self).welcome_email.deliver_now
  end

end

StudentAttendancePortal/app/controllers/students_controller.rb
class StudentsController < ApplicationController
  protect_from_forgery with: :null_session
  before_action :find_student, only: %i[show update destroy]

  def index
    @students = Student.all
  end

  def create
    @student = Student.new(student_params)
    respond_to do |format|
      if @student.save
        format.html { redirect_to student_url(@student), notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end  
  end

  def show
    @student = Student.find(params[:id])
  end

   # GET /students/new
   def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
   @student = Student.find(params[:id])
   render :edit
  end

  def update
    @student = Student.find(params[:id])
    if @student.update(student_params)
      redirect_to(@student)
    else
      render "edit"
    end
  end

  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: "Student was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def student_params
    params.require(:student).permit(:name, :email, :password, :dob, :gender, :address, :semister, :course)
  end

  def find_student
    @student = Student.find params[:id]
  rescue ActiveRecord::RecordNotFound => e
    render json: { meaasge: I18n.t('controller.present') }
  end
end

StudentAttendancePortal/app/helpers/students_helper.rb
module StudentsHelper
end

StudentAttendancePortal/app/views/students/_form.html.erb
<%= form_with(model: student) do |form| %>
  <table>
    <tr>
      <div>
        <td><%= form.label :name, "Name: " %></td>
        <td><%= form.text_field :name %></td>
      </div>
    </tr>
    <tr>
      <div>
        <td> <%= form.label :password, 'Password: '%></td>
        <td><%= form.password_field :password %></td>
      </div>
    </tr>
    <tr>
      <div>
        <td><%= form.label :password, 'Confirm -Password: '%></td>
        <td><%= form.password_field :password_confirmation %></td>
      </div>
    </tr>
    <tr>
      <div>
        <td><%= form.label :email,"Email: " %></td>
        <td><%= form.text_field :email %></td>
      </div>
    </tr>
    <tr>
      <div>
        <td><%= form.radio_button :gender, "Female" %>
          <%= form.label :Female, "Female" %></td>
        <td><%= form.radio_button :gender, "Male" %>
          <%= form.label :Male, "Male" %></td>
      </div>
    </tr>
    <tr>
      <div>
        <td><%= form.label :dob, "Date of birth: " %></td>
        <td><%= form.date_field :dob, as: :date, value: form.object.try(:strftime,"%m/%d/%Y")%></td>
      </div>
    </tr>
    <tr>
      <div>
        <td><%= form.label :semister, 'Semister: ' %></td>
        <td> <%= form.text_field :semister %></td>
      </div>
    </tr>
     <tr>
      <div>
        <td><%= form.label :course, 'course: ' %></td>
        <td> <%= form.text_field :course %></td>
      </div>
    </tr>
    <tr>
      <div>
        <td><%= form.label :address,'Address: ' %></td>
        <td><%= form.text_field :address %></td>
      </div>
    </tr>
  </table></br>

  <div class="col-3", style="margin: 0 auto;">
    <%= form.submit class: "btn btn-warning"%>
  </div>
<% end %>

StudentAttendancePortal/app/views/students/edit.html.erb
<div style="padding: 10px;">
  <%= link_to "Back to Students", students_path, class: "btn btn-success" %>    
</div>

<div class="col-6" style="margin : 0 auto;">
  <h1>Editing Student Details</h1></br>
  <%= render "form", student: @student %>
</div>

StudentAttendancePortal/app/views/students/index.html.erb
<div style="padding: 10px;">
  <%= link_to "HOME", welcome_index_path, class: "btn btn-success" %>    
</div>
<div class="col-4" style="margin : 0 auto; padding: 10px">
  <h1>All Students data</h1></br>
</div>
<table class="table table-striped">
  <thead class="thead-light">
    <tr>
      <td>ID</td>
      <td>Name</td>
      <td>Email</td>
      <td>Semister</td>
      <td>Course</td>
    </tr>
  </thead>
  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%=student.id%></td>
        <td><%= student.name %></td>
        <td><%= student.email %></td> 
        <td><%= student.semister %></td>
        <td><%= student.course %></td>
        <td><%= link_to 'show', student%></td>
      </tr>
   <% end %>
  </tbody>
</table>
<div class="col-2" style="margin : 0 auto; padding: 10px">
  <%= link_to 'Add new', new_student_path, class: "btn btn-success" %>
</div>

StudentAttendancePortal/app/views/students/new.html.erb
<div class="col-5"style="padding: 40px;">
  <%= link_to "Back to Students", students_path, class: "btn btn-success" %>    
</div>

<div class="col-4" style="margin : 0 auto;">
  <div class="col-8" style="margin : 0 auto;">
    <h1>New Student Entry</h1></br>
  </div>
  <%= render "form", student: @student %>
</div>

StudentAttendancePortal/app/views/students/show.html.erb
<div style="padding: 10px;">
  <%= link_to "Back to Students", students_path, class: "btn btn-success" %>    
</div>

<div class="col-6" style="margin : 0 auto;">
  <h2><%= @student.name %>'s  Details</h2></br></br>
  <h4>Name: <%= @student.name %></h4>
  <h4>Email: <%= @student.email %></h4>
  <h4>Date of birth: <%= @student.dob %></h4>
  <h4>Gender: <%= @student.gender %></h4>
  <h4>Address: <%= @student.address %></h4>
  <h4>Semister: <%= @student.semister %></h4>
  <h4>Course: <%= @student.course %></h4></br></br>
  <div class="d-flex justify-content-center">  
    <div class="col-2">
      <%= link_to "Edit", edit_student_path(@student), class: "btn btn-warning"%> 
    </div>
    <div class="col-3">
      <%= button_to "Destroy", @student, class: "btn btn-danger", data: {:confirm => 'Are you sure?'}, method: :delete %>
    </div>
  </div>
</div>