StudentAttendancePortal/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'welcome#index'
  resources :teachers, :subjects, :students, :attendances
  #patch 'teachers/:id', to: 'teachers#update'
end

StudentAttendancePortal/app/models/subject.rb
class Subject < ApplicationRecord
  belongs_to :teacher, optional: true
  has_many :attendance, dependent: :nullify
  has_many :subjects_students
  has_many :students, through: :subjects_students
end

StudentAttendancePortal/app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  protect_from_forgery with: :null_session
  before_action :find_subject, only: %i[show update destroy]

  def index
    @subjects = Subject.all
  end

  def create
    @subject = Subject.new(subject_params)
    respond_to do |format|
      if @subject.save
        format.html { redirect_to subject_url(@subject), notice: "subject was successfully created." }
        format.json { render :show, status: :created, location: @subject }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end 
  end

  def show
    @subject = Subject.find(params[:id])
  end

  def new
    @subject = Subject.new
    
  end

  def edit
    @subject = Subject.find(params[:id])   
    render :edit
  end

  def update
    @subject = Subject.find(params[:id])
    if @subject.update(subject_params)
      redirect_to(@subject)
    else
      render "edit"
    end
  end

  def destroy
    @subject.destroy
    respond_to do |format|
      format.html { redirect_to subjects_url, notice: "subject was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def subject_params
    params.require(:subject).permit(:name, :code, :teacher_id)
  end

  def find_teacher
    @teacher = Teacher.find params[:teacher_id]
  rescue ActiveRecord::RecordNotFound => e
    render json: { meaasge: I18n.t('controller.present') }
  end
  def find_subject
    @subject = Subject.find params[:id]
  rescue ActiveRecord::RecordNotFound => e
    render json: { meaasge: I18n.t('controller.present') }
  end
end

StudentAttendancePortal/app/helpers/subjects_helper.rb
module SubjectsHelper
end

StudentAttendancePortal/app/views/subjects/_form.html.erb
<%= form_with(model: subject) do |form| %>
  <table>
    <tr>
      <div>
        <td><%= form.label :name, "Name: " %></td>
        <td><%= form.text_field :name %></td>
      </div>
    </tr>
    <tr>
      <div>
        <td> <%= form.label :code, 'Code: '%></td>
        <td><%= form.text_field :code %></td>
      </div>
    </tr>
    <tr>
      <div>
        <td><%= form.label :teacher_id, 'Teacher name: '%></td>
        <td> <%= form.collection_select :teacher_id, Teacher.all, :id, :name, prompt: true %></td>
      </div>
    </tr>    
  </table></br>

  <div class="col-3", style="margin: 0 auto;">
    <%= form.submit class: "btn btn-warning"%>
  </div>
<% end %>

StudentAttendancePortal/app/views/subjects/edit.html.erb
<div style="padding: 10px;">
  <%= link_to "Back to Subjects", subjects_path, class: "btn btn-success" %>    
</div>

<div class="col-6" style="margin : 0 auto;">
  <h1>Editing Subject</h1></br>
  <%= render "form", subject: @subject %>
</div>

StudentAttendancePortal/app/views/subjects/index.html.erb
<div style="padding: 10px;">
  <%= link_to "HOME", welcome_index_path, class: "btn btn-success" %>    
</div>

<div class="col-4" style="margin : 0 auto; padding: 10px">
  <h1>All subjects data</h1></br>
</div>
<table class="table table-striped">
  <thead class="thead-light">
    <tr>
      <td>ID</td>
      <td>Name</td>
      <td>Code</td>
      <td>Teacher's ID</td>
    </tr>
  </thead>
  <tbody>
    <% @subjects.each do |subject| %>
      <tr>
        <td><%=subject.id%></td>
        <td><%= subject.name %></td>
        <td><%= subject.code %></td> 
        <td><%= subject.teacher_id %></td>
        <td><%= link_to 'show', subject%></td>
      </tr>
   <% end %>
  </tbody>
</table>
<div class="col-2" style="margin : 0 auto; padding: 10px">
<%= link_to 'Add new', new_subject_path, class: "btn btn-success" %>
</div>

StudentAttendancePortal/app/views/subjects/new.html.erb
<div class="col-5"style="padding: 40px;">
  <%= link_to "Back to Teachers", subjects_path, class: "btn btn-success" %>    
</div>

<div class="col-4" style="margin : 0 auto;">
  <div class="col-8" style="margin : 0 auto;">
    <h1>New Subject</h1></br>
  </div>
  <%= render "form", subject: @subject %>
</div>

StudentAttendancePortal/app/views/subjects/show.html.erb
<div style="padding: 10px;">
  <%= link_to "Back to Subjects", subjects_path, class: "btn btn-success" %>    
</div>

<div class="col-6" style="margin : 0 auto;">
  <h2><%= @subject.name %>'s  Details</h2></br></br>
  <h4>Name: <%= @subject.name %></h4>
  <h4>Code: <%= @subject.code %></h4>
  <h4>Teacher Id: <%= @subject.teacher_id %></h4>
  </br></br>
  <div class="d-flex justify-content-center">  
    <div class="col-2">
      <%= link_to "Edit", edit_subject_path(@subject), class: "btn btn-warning"%> 
    </div>
    <div class="col-3">
      <%= button_to "Destroy", @subject, class: "btn btn-danger", data: {:confirm => 'Are you sure?'}, method: :delete %>
    </div>
  </div>
</div>