StudentAttendancePortal/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'welcome#index'
  resources :teachers, :subjects, :students, :attendances
  #patch 'teachers/:id', to: 'teachers#update'
end

StudentAttendancePortal/app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :student, optional: true 
  belongs_to :subject, optional: true
end

StudentAttendancePortal/app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  protect_from_forgery with: :null_session
  #before_action :find_student, only: %i[create update]
  #before_action :find_attendance, only: %i[create update]
  #before_action :find_attendance, only: %i[show update destroy]

  def index
    @attendances = Attendance.all
  end

  def create
    @attendance = Attendance.new(attendance_params)
    respond_to do |format|
      if @attendance.save
        format.html { redirect_to attendance_url(@attendance), notice: "Attendance was successfully created." }
        format.json { render :show, status: :created, location: @attendance }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @attendance.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @attendance = Attendance.find(params[:id])
  end

  def new
    @attendance = Attendance.new
    
  end

  def edit
    @attendance = Attendance.find(params[:id])   
    render :edit
  end

  def update
    @attendance = Attendance.find(params[:id])
    if @attendance.update(attendance_params)
      redirect_to(@attendance)
    else
      render "edit"
    end
  end

  def destroy
    @status_update = Attendance.find(params[:id])
    if @status_update.present?
      @status_update.destroy
    end
    redirect_to attendances_url
  end



  private

  def attendance_params
    params.require(:attendance).permit(:status, :month, :time, :attendance_id, :student_id, :date)
  end

  def find_student
    @student = Student.find params[:student_id]
  rescue ActiveRecord::RecordNotFound => e
    render json: { meaasge: I18n.t('controller.present') }
  end

  def find_attendance
    @attendance = attendance.find params[:attendance_id]
  rescue ActiveRecord::RecordNotFound => e
    render json: { meaasge: I18n.t('controller.present') }
  end

  def find_attendance
    @attendance = Attendance.find params[:id]
  rescue ActiveRecord::RecordNotFound => e
    render json: { meaasge: I18n.t('controller.present') }
  end
  
end

StudentAttendancePortal/app/helpers/attendances_helper.rb
module AttendancesHelper
end

StudentAttendancePortal/app/views/attendances/_form.html.erb
<%= form_with(model: attendance) do |form| %>
  <table>
     <tr>
      <div>
        <td><%= form.label :status, "Status: " %></td>
        <td><%= form.select :status, ['Present', 'Absent']%></td>
      </div>
    </tr>
    <tr>
      <div>
        <td><%= form.label :month, "Month: " %></td>
        <td><%= form.select :month, Date::MONTHNAMES[1..12] %></td>
      </div>
    </tr>
     <tr>
      <div>
        <td><%= form.label :time, "Time: " %></td>
        <td><%= form.time_select :time, :discard_hour => true, :default => {:minute => '00', :second => '00'}, :include_seconds => true %></td>
      </div>
    </tr>
     <tr>
      <div>
        <td><%= form.label :date, "Date : " %></td>
        <td><%= form.date_field :date, as: :date, value: form.object.try(:strftime,"%m/%d/%Y")%></td>
      </div>
    </tr>
    <tr>
      <div>
        <td><%= form.label :subject_id, 'Subject name: '%></td>
        <td> <%= form.collection_select :subject_id, Subject.all, :id, :name, prompt: true %></td>
      </div>
    </tr> 
    <tr>
      <div>
        <td><%= form.label :student_id, 'Student name: '%></td>
        <td> <%= form.collection_select :student_id, Student.all, :id, :name, prompt: true %></td>
      </div>
    </tr>    
  </table></br>

  <div class="col-3", style="margin: 0 auto;">
    <%= form.submit class: "btn btn-warning"%>
  </div>
<% end %>

StudentAttendancePortal/app/views/attendances/edit.html.erb
<div style="padding: 10px;">
  <%= link_to "Back to Attendance", attendance_path, class: "btn btn-success" %>    
</div>

<div class="col-6" style="margin : 0 auto;">
  <h1>Editing Attendance</h1></br>
  <%= render "form", attendance: @attendance %>
</div>

StudentAttendancePortal/app/views/attendances/index.html.erb
<div style="padding: 10px;">
  <%= link_to "HOME", welcome_index_path, class: "btn btn-success" %>    
</div>

<div class="col-4" style="margin : 0 auto; padding: 10px">
  <h1>All Attendance data</h1></br>
</div>
<table class="table table-striped">
  <thead class="thead-light">
    <tr>
      <td>ID</td>
      <td>attendance Status</td>
      <td>Student Name</td>
      <td>Subject</td>
      <td>Time</td>
    </tr>
  </thead>
  <tbody>
    <% @attendances.each do |attendance| %>
      <tr>
        <td><%=attendance.id%></td>
        <td><%= attendance.status %></td>
        <td><%= attendance.student_id %></td> 
        <td><%= attendance.subject_id %></td>
        <td><%= link_to 'show', attendance%></td>
      </tr>
   <% end %>
  </tbody>
</table>
<div class="col-2" style="margin : 0 auto; padding: 10px">
<%= link_to 'Add new', new_attendance_path, class: "btn btn-success" %>
</div>

StudentAttendancePortal/app/views/attendances/new.html.erb
<div class="col-5"style="padding: 40px;">
  <%= link_to "Back to Attendance", attendances_path, class: "btn btn-success" %>    
</div>

<div class="col-4" style="margin : 0 auto;">
  <div class="col-8" style="margin : 0 auto;">
    <h1>New Attendance</h1></br>
  </div>
  <%= render "form", attendance: @attendance %>
</div>

StudentAttendancePortal/app/views/attendances/show.html.erb
<div style="padding: 10px;">
  <%= link_to "Back to Attendances", attendances_path, class: "btn btn-success" %>    
</div>

<div class="col-6" style="margin : 0 auto;">
  <h2><%= @attendance.time %>'s  Details</h2></br></br>
  <h4>Status: <%= @attendance.status %></h4>
  <h4>Subject Id: <%= @attendance.subject_id %></h4>
  <h4>Student Id: <%= @attendance.student_id %></h4>
  <h4>Date: <%= @attendance.date %></h4>
  <h4>Time: <%= @attendance.time %></h4>
  </br></br>
  <div class="d-flex justify-content-center">  
    <div class="col-2">
      <%= link_to "Edit", edit_attendance_path(@attendance), class: "btn btn-warning"%> 
    </div>
    <div class="col-3">
      <%= button_to "Destroy", @attendance, class: "btn btn-danger", data: {:confirm => 'Are you sure?'}, method: :delete %>
    </div>
  </div>
</div>